org: jamesdev

service: Softtek-Prueba-Tecnicav2

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-2:481665110873:table/Sofftekv2"

functions:
  getPeoples:
    handler: src/people/functions/getPeoples.handler
    events:
      - httpApi:
          path: /people
          method: GET
  getPeople:
    handler: src/people/functions/getPeople.handler
    events:
      - httpApi:
          path: /people/{id}
          method: GET
  createPeople:
    handler: src/people/functions/createPeople.handler
    events:
      - httpApi:
          path: /people
          method: POST
  updatePeople:
    handler: src/people/functions/updatePeople.handler
    events:
      - httpApi:
          path: /people/{id}
          method: PUT

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Sofftekv2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
package:
  exclude:
    - node_modules/**
    - test/**
    - .git/**
    - .env