// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Softtek-Prueba-Tecnica",
    "version": "1"
  },
  "paths": {
    "/people": {
      "get": {
        "summary": "getPeoples",
        "description": "",
        "operationId": "getPeoples.get./people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "createPeople",
        "description": "",
        "operationId": "createPeople.post./people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};