export const englishToSpanishMapping: Record<string, string> = {
  id: "id",
  birth_year: "anio_nacimiento",
  eye_color: "color_ojos",
  films: "peliculas",
  gender: "genero",
  hair_color: "color_cabello",
  height: "altura",
  homeworld: "planeta_natal",
  mass: "masa",
  name: "nombre",
  skin_color: "color_piel",
  species: "especies",
  starships: "naves_estelares",
  vehicles: "vehiculos",
  url: "url",
  created: "creado",
  edited: "editado",
};
